"""Build a merged (base + patch) app GP4 for LibOrbisPkg's PkgTool.

Files from the patch override files from the base; patch-only delta metadata
is dropped so the result is a plain full-game (gd) package at APP_VER 01.03.
"""
import os
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

WORK = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(WORK, "base")
PATCH = os.path.join(WORK, "patch")
OUT_DIR = os.path.join(WORK, "merged")
PKGTOOL = sys.argv[1]

# Delta/patch bookkeeping that must not end up in an app package.
# playgo-chunk.dat is regenerated by PkgTool from <chunk_info>, as for the base.
PATCH_ONLY_SKIP = {
    "sce_discmap_patch.plt",
    "sce_sys/origin-deltainfo.dat",
    "sce_sys/app/playgo-chunk.dat",
}


def file_map(gp4_path):
    root = ET.parse(gp4_path).getroot()
    return {f.get("targ_path"): f.get("orig_path") for f in root.iter("file")}


def main():
    base_files = file_map(os.path.join(BASE, "Project.gp4"))
    patch_files = file_map(os.path.join(PATCH, "Project.gp4"))

    os.makedirs(os.path.join(OUT_DIR, "sce_sys"), exist_ok=True)
    sfo = os.path.join(OUT_DIR, "sce_sys", "param.sfo")
    shutil.copyfile(os.path.join(PATCH, "sce_sys", "param.sfo"), sfo)
    subprocess.run([PKGTOOL, "sfo_setentry", "--value", "gd", sfo, "CATEGORY"], check=True)

    merged = {t: os.path.join(BASE, o) for t, o in base_files.items()}
    # PFS path lookup is case-insensitive (the path hash upper-cases names), so a patch
    # file overrides a base file that differs only in case (MK11: base .xxx, patch .XXX).
    by_lower = {t.lower(): t for t in merged}
    for t, o in patch_files.items():
        if t not in PATCH_ONLY_SKIP:
            merged.pop(by_lower.get(t.lower()), None)
            merged[t] = os.path.join(PATCH, o)
    merged["sce_sys/param.sfo"] = sfo

    missing = [p for p in merged.values() if not os.path.isfile(p)]
    if missing:
        sys.exit(f"missing source files: {missing[:5]}")

    # Patch GP4 carries the newer volume timestamp and package settings.
    tree = ET.parse(os.path.join(PATCH, "Project.gp4"))
    root = tree.getroot()
    files_el = root.find("files")
    for f in list(files_el):
        files_el.remove(f)
    for t in sorted(merged, key=lambda t: (not t.startswith("sce_sys/"), t)):
        el = ET.SubElement(files_el, "file")
        el.set("targ_path", t)
        el.set("orig_path", merged[t])
    # Derive the dir tree from the merged file list: the patch may add dirs
    # (e.g. sce_sys/changeinfo) that the base tree lacks, and PkgTool fails on those.
    # Start from the base tree so empty dirs survive.
    root.remove(root.find("rootdir"))
    rootdir = ET.parse(os.path.join(BASE, "Project.gp4")).getroot().find("rootdir")
    root.append(rootdir)
    nodes = {"": rootdir}

    def index(el, prefix):
        for d in el.findall("dir"):
            key = prefix + d.get("targ_name")
            nodes[key] = d
            index(d, key + "/")

    index(rootdir, "")
    for t in sorted(merged):
        parts = t.split("/")[:-1]
        for i in range(len(parts)):
            key = "/".join(parts[: i + 1])
            if key not in nodes:
                el = ET.SubElement(nodes["/".join(parts[:i])], "dir")
                el.set("targ_name", parts[i])
                nodes[key] = el

    ET.indent(tree)
    tree.write(os.path.join(OUT_DIR, "Project.gp4"), encoding="utf-8", xml_declaration=True)
    print(f"base={len(base_files)} patch={len(patch_files)} merged={len(merged)}")


if __name__ == "__main__":
    main()
